### ISSUE TITLE
As a user, I want to see a loading icon instead of a broken picture when adding files.

### ISSUE THREAD

**Issue by Endlessflow** [ai-cfia/fertiscan-frontend#119]
# Bug Report

## Description

**Bug Summary:**
Users encounter a broken picture icon in the file list when there is upload latency after selecting a file and clicking "Add."

**Steps to Reproduce:**
1. Navigate to HomePage.
2. Click on "Add file."
3. Select any file from the local system using the file picker.
4. Click on "Add" to upload the selected file.

**Expected Behavior:**
When a user selects a file and clicks on "Add," there should be an indication of progress, such as a loading spinner, until the file is fully uploaded and displayed correctly in the list.

**Actual Behavior:**
Instead of showing a loading icon during upload latency, a broken picture icon appears in the file list which can confuse users into thinking that something went wrong with their upload.

## Environment
- Affected Page: HomePage

## Logs and Screenshots
**Screenshots:**
[Attach screenshot showing broken picture icon]

**Comment by Youllou** [comment]
The broken picture appears for a few second (if not less than a second).
This could be nice to have but clearly isnt ux breaker

**Comment by SamuelPelletierEvraire** [comment]
old main project
