### ISSUE TITLE
Refactor big if sequence with a dictionary

### ISSUE THREAD

**Issue by MaxenceGui** [ai-cfia/fertiscan-frontend#12]
### Description :rocket:

Checking properties for harvester is done in a long list of if. To make the code easier to read and to maintain, I suggest the use of a dictionary and a for loop.

### Steps by Steps :📋 

- Create a property dictionary as a CONSTANT (could even be an environment variable)
- Refactor the long if using `.items()`
- Validate that the program work

### Effort and Impact 🏃🏻 

This is not hard to implement and it will really help the code readability.

### Acceptance criteria ✅  

- The program behave the same as before

**Comment by SamuelPelletierEvraire** [comment]
s
