### ISSUE TITLE
Unsaved Data Loss on Navigation Between SettingPage and FormPage

### ISSUE THREAD

**Issue by Endlessflow** [ai-cfia/fertiscan-frontend#122]
## Description
Bug Summary:
Navigating from FormPage to SettingPage and back causes FormPage to reload and unsaved user data to be lost.

## Steps to Reproduce:

1. Enter data into various fields on FormPage.
2. Navigate to SettingPage using the side menu.
3. Return to FormPage by navigating through the side menu.

## Expected Behavior:
When switching between SettingPage and FormPage, the data entered on FormPage should persist and not be lost, allowing seamless back-and-forth navigation without the need to save every time before leaving the page.

## Actual Behavior:
Upon returning to FormPage after visiting SettingPage, the page reloads, resulting in the loss of all unsaved input data.

## Environment
Pages: SettingPage & FormPage

## Logs and Screenshots
Not able to recreate the bug.

**Comment by k-allagbe** [comment]
Can't reproduce. Has this been fixed elsewhere? @Youllou @Samuelpelletier3124
