### ISSUE TITLE
Removing the Modal for Text Display in Favor of Direct Text Area Height Adjustment

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#130]
## Description:
The current implementation of our application includes a modal pop-up that displays text content when users interact with certain text areas. Feedback and usability studies have suggested that the modal does not contribute significantly to the user experience and can be perceived as an unnecessary step in the workflow. The additional action of opening and closing the modal to view text is considered a hindrance rather than a helpful feature.

Users frequently need more space to view or edit longer text fields and would benefit from a simpler solution. The proposed change involves removing the modal and allowing users to adjust the text area's height directly with the mouse for immediate and seamless editing or viewing.

### Scope of Issue:
- The modal mechanism that activates to display text in specific areas of our application.

### Goals:
1. To remove the modal functionality that currently exists for displaying text content.
2. To enable direct resizing of text areas by implementing a 'drag to adjust height' feature with the mouse, thus improving user control and accessibility.
3. To update the application's interface to be more intuitive, removing unnecessary steps and streamlining the text-editing process.
4. To ensure no regression in functionality and maintain or improve the overall user experience.
5. To update and refactor any affected components, services, or states that depend on the modal feature.

### Acceptance Criteria:

- [ ]  The modal pop-up feature is successfully removed from the application.
- [ ]  The text areas now have a user-friendly resizing handle that allows height adjustment using the mouse.
- [ ]  Resizing of the text area is smooth, retains its functionality, and there are no display or formatting issues post-resize.
- [ ] -All functionalities that previously depended on the modal display are still operational and have been adapted to work with the directly resizable text area.
- [ ]  Thorough testing confirms that the changes do not introduce new bugs or regress existing features.

### Out of Scope:
- Redesigning the UI/UX of the text areas apart from the height adjustment feature.
- Implementing any new features or changes unrelated to the modal removal and text area resizing.

**Comment by k-allagbe** [comment]
@Youllou @Samuelpelletier3124 should we close this?
