### ISSUE TITLE
Add indication on DragAndDropComponent to specify user where to upload file.

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#132]
## Description:
The current DragAndDropComponent does not provide clear visual indicators to guide users on where to upload their files. This lack of guidance may result in confusion and errors, impeding the overall user experience. The objective is to augment the component's usability by introducing distinct cues that demarcate the drop zone for file uploads.

### Expected Behavior
Users should receive instantaneous and unmistakable feedback on where to drag and drop their files within the interface. The design should incorporate visual elements and accessible instructions that improve the user journey and reinforce an intuitive interaction with the file upload feature.

### Acceptance Criteria

- [x] A visible boundary or highlight appears around the drop zone when users initiate a drag-over action.
- [x] Clear instructions are displayed to users about the drag-and-drop action, without disrupting the workflow.
- [x] The interaction evokes a reliable drag-and-drop experience, indicating successful file uploads.
- [x] The users should be able to understand the drag-and-drop functionality and complete the upload process without needing additional guidance.

#### **Drop Zone Visual Indicator**

- **Specification:** Add a highlighted border or shade contrast to the drop zone area when a user drags files over it.
- **Purpose:** To give a clear and immediate visual cue that delineates the designated area for file uploads.

#### **Dynamic Feedback During Drag-Over**

- **Specification:** Introduce a change in the appearance of the drop zone (such as a shadow or color adjustment) during a file drag-over action.
- **Purpose:** To visually reassure users that they are interacting with the correct area for their file upload task.

#### **Instructional Prompts**

- **Specification:** Provide persistent or dynamically appearing text instructions within or near the drop zone, guiding the user to "Drag and drop your files here" or "Release files to upload."
- **Purpose:** To deliver straightforward guidance and enhance the user's confidence in performing the upload action.

**Comment by k-allagbe** [comment]
@Samuelpelletier3124 should we close this?
