### ISSUE TITLE
As a user, I want to be able to see a list of all saved labels

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#176]
## Description  

Add a button to the sidenav to access a new page which displays a list of labels.

**Acceptance Criteria**

- [x] A page is created to display the list of saved labels
- [x] The page is accessible through the sideNav
- [ ] The state of the main workflow isnt lost on accessing the page

Each element in the list should look like

![Image](https://github.com/user-attachments/assets/4fe18090-5757-44e8-9ee9-74da7f48a692)

**Comment by k-allagbe** [comment]
Tested, works as expected.
