### ISSUE TITLE
As a user, I want to be able to access the details of a saved label

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#178]
## Description  

I want to be able to click on a label listed in the list page and see all the details of the form. It would be nice to be presented the same display as the confirmation page.
For now, I should NOT be able to modify the label.

**Acceptance Criteria** 

- [x] A label listed in the list page is clickable
- [x] When clicked, the details of the clicked label are displayed
- [x] I can go back to the list page
- [x] The state of the main workflow isn't lost on accessing the details of a label.

**Comment by k-allagbe** [comment]
Tested, works as expected.
