### ISSUE TITLE
As a user, I want to have all the field translate on the form and confirmation page.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#182]
## Description  

**Bug Summary:**
Not all field in the form and in the confirmation page are translated into French.
![image](https://github.com/user-attachments/assets/e96fa572-5425-4999-bfb5-9ace84461815)

**Steps to Reproduce:**  
Go to the form page by uploading a picture.
Click on submit.

**Expected Behavior:**  
Those fields should be translated.

**Actual Behavior:**  
Those fields are not translated.

**Comment by k-allagbe** [comment]
@snakedye @Endlessflow this is actually coming from the pipeline. I don't think the field names should be translated, but the values won't change from english to french if I'm correct. Would that mean that we only need specifications and not specifications_en & specifications_fr?

**Comment by k-allagbe** [comment]
These fields will be deleted from the form in Iteration 6. Closing this.
