### ISSUE TITLE
As a dev, I want to refactor the `AlertProvider` component.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#194]
# Description
The purpose of this task is to conduct a comprehensive refactoring of the AlertProvider component in the FertiScan project. The focus will be on improving the component's design, ensuring its efficient operation, and aligning it with the latest development practices. This will include a review and enhancement of the component's state management, theming capabilities, and API usage.

## Task
Refactor the AlertProvider.

## Acceptance criteria
- [ ] The AlertProvider component functions correctly and integrates seamlessly with existing and new features that require alert functionality.
- [ ] The code is clean, concise, and well-documented, using the new code convention of the Ai-Lab team.

**Comment by k-allagbe** [comment]
Done in #307.

Show Alert:
```typescript
const { showAlert } = useAlertStore();

showAlert({
  type: "error",        // Options: "error", "info", etc.
  message: "This is an error message."
});
```

Hide Alert:
```typescript
const { hideAlert } = useAlertStore();
hideAlert();
```

> [!NOTE]  
> The alert will auto-dismiss after 5 seconds if not hovered over.
