### ISSUE TITLE
As a dev, I want to explore Redux as a replacement for Context API for State Management

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#204]
## Description

**Context**  
We are currently using React's Context API for state management. While it works well for our current needs, we want to explore Redux as a way to learn new state management techniques. Additionally, we have noticed inefficiencies with Context, such as unnecessary component re-renders when the global state changes.

**Problem Statement**  
We want to transition from Context to Redux as part of our team's learning process. Redux’s centralized state management could help us avoid unnecessary re-renders and provide more predictable control over state updates. Though performance improvements are not a primary concern, they would be a bonus during this transition.

## Acceptance Criteria
- Implement Redux to manage global state instead of Context.
- Reduce unnecessary re-renders by ensuring state updates only affect the relevant components.
- Ensure the application functions correctly after the transition to Redux.
- Optionally assess any performance changes after implementing Redux.

## Additional Information 
- [Blogged Answers: Why React Context is Not a "State Management" Tool (and Why It Doesn't Replace Redux)](https://blog.isquaredsoftware.com/2021/01/context-redux-differences/)
- [Redux Essentials, Part 1: Redux Overview and Concepts](https://redux.js.org/tutorials/essentials/part-1-overview-concepts)

**Comment by SamuelPelletierEvraire** [comment]
# Streamlined Documentation for State Management in React: Transitioning from useState to Redux

## Introduction 

In the realm of React application development, the pivotal role of state management cannot be overstated. Effortlessly managing state at the initial stages with React's `useState` hook can become arduous as applications expand in complexity. For scenarios that exceed `useState`'s capacity, Redux emerges as a substantial contender, offering a global state container designed for predictability and scale. This guide outlines the merits of adopting Redux over `useState` and elucidates the migration pathway through a practical example.

## Redux's Superiority Over useState

### Centralization of Application State

`useState` proves valuable for insular state management within components; nonetheless, Redux excels with a central repository of state, accessible application-wide, curtailing the intricate prop threading and augmenting state predictability.

### Augmented Debugging Capabilities

Redux's developer arsenal includes advanced debugging tools, such as Time Travel, to seamlessly traverse state transformations, fostering a clearer comprehension of data transitions within the application.

### Middleware Extensions

Redux middleware, including Redux Saga and Redux Thunk, introduces a coherent mechanism for orchestrating side-effects and asynchronous actions, invaluable for managing elaborate workflows such as API transactions.

### Performance Tuning for Complex Applications

High update frequencies can overwhelm the `useState` hook, leading to gratuitous component re-renders. Redux refines application performance by pinpointing component update triggers, resulting in judicious re-rendering.

### Code Maintainability and Growth

Redux advocates a structured state management methodology using actions and reducers, which simplifies code maintenance and upscaling as the application's scope widens.

## Practical Migration: From useState to Redux

Consider a rudimentary counter component transitioning from `useState` to Redux:

### Original Component with useState

```jsx
import React, { useState } from 'react';

function Counter() {
  const [count, setCount] = useState(0);

  return (
    <div>
      <p>{count}</p>
      <button onClick={() => setCount(count + 1)}>
        Increment
      </button>
    </div>
  );
}

export default Counter;
```

### Transition Steps to Redux

#### Step 1: Setting Up Redux Dependencies

```bash
npm install redux react-redux
```

#### Step 2: Configuring the Redux Store

Create `store.js` with a reducer function:

```javascript
import { createStore } from 'redux';

function counterReducer(state = { count: 0 }, action) {
  switch (action.type) {
    case 'INCREMENT':
      return { ...state, count: state.count + 1 };
    default:
      return state;
  }
}

export default createStore(counterReducer);
```

#### Step 3: Integrating Redux Store with React

Wrap the root component with `react-redux`'s `Provider` in `index.js` or `App.js`:

```javascript
import { Provider } from 'react-redux';
import store from './store';
import Counter from './Counter';

function App() {
  return (
    <Provider store={store}>
      <Counter />
    </Provider>
  );
}

export default App;
```

#### Step 4: Reconnecting the Counter Component to Redux

```jsx
import React from 'react';
import { useSelector, useDispatch } from 'react-redux';

function Counter() {
  const count = useSelector(state => state.count);
  const dispatch = useDispatch();

  return (
    <div>
      <p>{count}</p>
      <button onClick={() => dispatch({ type: 'INCREMENT' })}>
        Increment
      </button>
    </div>
  );
}

export default Counter;
```

## Harnessing Performance Improvements

Efficiency in web applications splits into render performance and state management robustness. Below are some concrete illustrations of how performance can be fine-tuned across these domains.

Performance in web applications can be broadly divided into two aspects: rendering performance and state management performance. Here are some examples that demonstrate how performance can be optimized in both areas.

### Rendering Performance Example

**Problem:** Suppose a React component is re-rendering too often, causing a decrease in performance.

**Solution:** You can use `React.memo` for a functional component or `shouldComponentUpdate` lifecycle method for class components to prevent unnecessary re-renders.

```jsx
// Functional component with React.memo
const MyComponent = React.memo(function MyComponent({ prop }) {
  // The component only re-renders if prop changes
  return <div>{prop}</div>;
});

// Class component with shouldComponentUpdate
class MyComponent extends React.Component {
  shouldComponentUpdate(nextProps, nextState) {
    // Only re-render if the prop has changed
    return nextProps.prop !== this.props.prop;
  }

  render() {
    return <div>{this.props.prop}</div>;
  }
}
```

### State Management Performance Example

**Problem:** An application using `useState` experiences performance issues because changes in the state at the top-level component cause massive re-renders in child components, even when it's not necessary for them to update.

**Solution:** Migrate state management to Redux and use `reselect` to memoize selectors, thereby preventing child components from re-rendering unless specific pieces of the state they depend on have changed.

```javascript
import { createSelector } from 'reselect';

// Suppose your Redux state structure looks like this:
// state = {
//   user: { name: 'Alice', age: 30 },
//   posts: { ... }
// }

// Create a memoized selector using `reselect`
const selectUserName = createSelector(
  state => state.user.name,
  name => name
);

const MyProfileComponent = () => {
  // This component only re-renders when the user's name changes.
  const userName = useSelector(selectUserName);

  return <div>{userName}</div>;
};
```

### Performance Monitoring Example

**Problem:** Your application seems to be slow, but you're not sure which components or processes are causing the lag.

**Solution:** Use performance monitoring tools like the React DevTools profiler to identify bottlenecks.

```bash
# Add React DevTools to your project
npm install --dev react-devtools
```

After installing, you can run the `react-devtools` and use the profiling capabilities to check which components are taking the longest to render, and optimize accordingly.

### Code Splitting Example

**Problem:** A large bundle size is causing your application to load slowly, particularly on first page load.

**Solution:** Implement code-splitting using `React.lazy` and `Suspense` to break up your app into smaller chunks that can be loaded on-demand.

```jsx
import React, { Suspense, lazy } from 'react';

const OtherComponent = lazy(() => import('./OtherComponent'));

function MyComponent() {
  return (
    <div>
      <Suspense fallback={<div>Loading...</div>}>
        <OtherComponent />
      </Suspense>
    </div>
  );
}
```

**Comment by k-allagbe** [comment]
Closing this. We'll explore zustand instead.
