### ISSUE TITLE
As an inspector, I want a “Notes/Comments” section added to the label inspection form

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/fertiscan-frontend#227]
## Description
We need a solution for inspectors to add relevant notes or comments to the label inspection data. A section for free-text input will be added.

**Acceptance Criteria**  
- [ ] Add a section to the inspection schema for free-form notes or comments. 
- [ ] Name the section appropriately.

**Additional Information**  
Ensure the section aligns with the schema as per https://github.com/ai-cfia/ailab-datastore/issues/151

**Comment by Francois-Werbrouck** [comment]
I suggest adding a field into the inspection JSON like the following: 
```JSON
{
  "inspection_id": "uuid",
 "inspection_comment": "some comment/ user feedback in text",
  "verified": false,
  "product": {
...
```

**Comment by k-allagbe** [comment]
After testing, submission crashes the app. Reopening this.
