### ISSUE TITLE
As an inspector, I want the label inspection form to reflect the requested changes

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/fertiscan-frontend#228]
## Description

**Context**  
The label inspection form needs to be updated to reflect changes agreed upon in the recent user meeting.

**Problem Statement**  
The current inspection schema contains sections that are no longer needed, and some sections require changes to align with the agreed standards.

**Acceptance Criteria**  
- Keep the `guaranteed_analysis` section, and ensure it is available in both French and English (FR and EN).  
- Remove the `first_aid` section.  
- Remove the `micronutrients` section. 
- Remove the `specification` section.  
- Remove the `warranty*` section.  

**Additional Information**  
Refer to https://github.com/ai-cfia/fertiscan-pipeline/issues/22 for details on the changes to the label analysis data format.

**Comment by Francois-Werbrouck** [comment]
I've updated the documentation of the epic to display the new inspection JSON 💯
