### ISSUE TITLE
As a dev, I want the front-end to respect the GoC accessibility standards and CFIA visual identity

### ISSUE THREAD

**Issue by RussellJimmies** [ai-cfia/fertiscan-frontend#248]
### Description
As part of our commitment to inclusivity and adherence to government digital standards, we want our app to comply with the [Canadian Accessibility Standards](https://a11y.canada.ca/en/accessibility-standards/). This ensures that all users, including those with disabilities, can effectively interact with and navigate our application.

Additionally, the front-end should respect the Treasury Board's [Federal Identity Program](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/federal-identity-program.html), as well as the CFIA's visual identity.

### Acceptance Criteria
- [ ] [Satisfy all checks on Web Accessibility Checklist](https://a11y.canada.ca/en/web-accessibility-checklist/)
- [ ] Respect the Treasury Board's [Federal Identity Program](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/federal-identity-program.html)
- [ ] [Respect the Alpha Canada requirements](https://alpha.canada.ca/en/instructions.html)

### Additional Information
- Consider reviewing the [W3C Web Content Accessibility Guidelines (WCAG) 2.1](https://www.w3.org/WAI/WCAG21/quickref/) for reference. This is THE guideline in regards to creating accessible web content, adopted by the GoC. 
- [Accessiblity testing](https://a11y.canada.ca/en/accessibility-testing-101/): Automated accessibility testing tools
- [Web Experience Toolkit](https://wet-boew.github.io/v4.0-ci/index-en.html): Front-End framework for building websites that are mobile accessible, usable, interoperable, mobile friendly, and multilingual
- [Canada Content Style Guide](https://design.canada.ca/style-guide/)

**Comment by k-allagbe** [comment]
Closing this as done. I'll reference this issue in our refactor issues.

**Comment by k-allagbe** [comment]
This will be used as reference in #257. Closing this as done.
