### ISSUE TITLE
As a user, I want the confirm page to work as intended

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#255]
## Description  

**Bug Summary:** 
As of right now, when arriving on the confirm page we are just prompted a blanck screen

**Steps to Reproduce:**  
Do the classic workflow up to the confirmpage

**Expected Behavior:**  
See the label I was completing

**Actual Behavior:**  
Blank page

**Additional Context:**  
This happens since the modification on the structure of a label (guaranteed analysis title, comments, ...)

**Suggested Fix:** 
My guess is the label component is not able to work with those changes
check `src/Components/Label`

**Comment by k-allagbe** [comment]
Can't reproduce this. Closing this. Please reopen if this issue is observed again. Do not forget to add logs and the image used.
