### ISSUE TITLE
As a dev, I want to explore react frameworks to improve our development speed and modernize our frontend

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/fertiscan-frontend#256]
## Description

**Context**  
We currently use React in a bare/vanilla form for our frontend development. While this has been functional, we want to explore newer and more modern open-source frameworks that could help us work more efficiently, improve performance, and modernize our codebase. This is part of a broader initiative to enhance our frontend architecture and keep up with current best practices in the industry.

**Problem Statement**  
We need to evaluate various modern react frameworks and determine which one would best fit our needs, offering better performance, development speed, maintainability, and potential long-term advantages. The goal is to make an informed decision on whether to continue with React vanilla or switch to a newer framework.

## Acceptance Criteria  
- Perform a comparative analysis of react frameworks. The comparison should focus on factors like open source licences, development speed, performance, ease of use, ecosystem support, and scalability. 
- Assess the effort required for migration, including potential timelines, complexity, and any key areas of concern for transitioning to the recommended framework.
- Provide a clear recommendation on whether to continue using React vanilla or switch to another framework, based on the analysis.

## Additional information
- [Start a New React Project](https://react.dev/learn/start-a-new-react-project#production-grade-react-frameworks): good info source
- [State of JS 2023](https://2023.stateofjs.com/en-US/libraries/)
- [State of React 2023](https://2023.stateofreact.com/en-US/libraries/)

**Comment by Youllou** [comment]
Here is a list of really interesting frameworks that could be used for the frontend
# Next JS
Next JS is a Framework that brings many upgrade to React. It gives the ability to make server side rendering which is way more secure. This combined with static generation which pre-render pages at build instead of on each request, makes most request much lighter and much faster. It also gives the ability to use API routes (we might be able to get rid of nginx for this)
NextJS gives us the ability to uses Sass but I'm not sure if this should be done or not (see Sass point)

# Material-UI
MUI gives a full control on customization and styling. It gives some amazing tools for responsiveness with grid classes that are responsive.
It also includes a bunch of tools to control the color and appearance of any component and even gives some pre-coded components like buttons.

# Styled components
This framework makes it possible to add the style-sheet directly in the ts file. This is much useful as it will also bind the style-sheet to this ts file by giving a special class to any component that comes out of this file.
It makes the naming convention much simpler as we are assured that two css classes with the same name wont interfere on each other

# Sass
Sass (Syntactically Awesome StyleSheets) is a preprocessor for CSS. It offers more power and elegance to CSS but is sure more complex and add a layer of complexity to our project (moreover if use styled-components as scss files would need to be compiled before being adedd to the ts files)

**Comment by k-allagbe** [comment]
# Vanilla React vs Next.js Vs Gatsby

| **Feature/Aspect**        | **Vanilla React**                                                                                         | **Next.js**                                                                                          | **Gatsby**                                                                                                                                    |
| ------------------------- | --------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------- |
| **Type**                  | UI library for building components                                                                        | Full-stack framework for SSR, SSG, and API routes                                                    | Static site generator, optimized for SSG and SSR                                                                                              |
| **Routing**               | External libraries (e.g., React Router)                                                                   | Built-in file-based routing                                                                          | Built-in file-based routing                                                                                                                   |
| **Performance**           | Depends on manual optimizations                                                                           | High performance with SSR, code splitting                                                            | Optimized for static sites; good performance                                                                                                  |
| **Developer Experience**  | Full control over setup and configurations; manual setup of tools and libraries; large community support. | Easy to start with minimal setup; built-in features like SSR/SSG; user-friendly and well-documented. | Lots of plugins and themes; learning GraphQL can be challenging; great for static sites; good tools but may require adapting to its approach. |
| **Ecosystem & Community** | Large, mature, abundant resources                                                                         | Mature, widely adopted, extensive documentation                                                      | Active community                                                                                                                              |
| **Use Cases**             | Flexible UIs for web apps of any size                                                                     | Complex apps, e-commerce, dynamic websites                                                           | Static sites, content-rich websites                                                                                                           |

## Pros & Cons

### Vanilla React

**Pros:**

- **Flexibility:** Full control over project setup and configuration.
- **Lightweight:** Minimal abstractions, which can mean better performance for simple apps.
- **Large Ecosystem:** Many libraries and tools available for various needs.

**Cons:**

- **Setup Overhead:** Requires manual setup for tools like bundlers and routing.
- **Missing Features:** Lacks built-in features like routing or state management.

### Next.js

**Pros:**

- **Server-Side Rendering (SSR):** Boosts performance by rendering pages on the server. This also adds a layer of security by keeping secrets on the server side.
- **Static Site Generation (SSG):** Speeds up loading by pre-rendering pages at build time.
- **Built-in Routing:** File-based routing system simplifies navigation setup.
- **Structured Approach:** Enforces a clear project structure for best practices.

**Cons:**

- **Learning Curve:** Introduces new concepts and abstractions unfamiliar to those used to Vanilla React.
- **Overkill for Small Projects:** May add unnecessary complexity for simple apps.

### Gatsby

**Pros:**

- **Static Site Generation:** Great for fast, static websites.
- **Performance Features:** Built-in optimizations like image handling and prefetching.
- **Plugin System:** Offers numerous plugins for data integration and extra functionality.

**Cons:**

- **Slow Build Times:** Large projects can experience slow builds.
- **GraphQL Overhead:** Requires GraphQL for data fetching, which has a learning curve.
- **Not Ideal for Dynamic Content:** Less suitable for apps needing frequent real-time data updates.

## References

- [React Documentation](https://reactjs.org/docs/getting-started.html)
- [Next.js Documentation](https://nextjs.org/docs)
- [Gatsby Documentation](https://www.gatsbyjs.com/docs/)
- [Next.js vs Gatsby: A Comprehensive Comparison](https://www.raftlabs.com/blog/next-js-vs-gatsby-a-comprehensive-comparison/)
- [Start a New React Project](https://react.dev/learn/start-a-new-react-project#production-grade-react-frameworks)

**Comment by k-allagbe** [comment]
Closing this as done. We'll move forward with nextjs.
