### ISSUE TITLE
As a user, I want to upload more images without size limitations by removing the reliance on session storage

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/fertiscan-frontend#263]
## Description  

**Context**  
We currently use session storage to temporarily store uploaded images in order to prevent progress from being lost if the user accidentally reloads the page. However, session storage is limited in capacity (typically a few MBs), which restricts the number and size of images users can upload. After review, we decided that a better solution is to alert the user before they refresh the page rather than relying on session storage to maintain progress.

**Problem Statement**  
We need to remove the use of session storage for holding uploaded images, as it imposes size restrictions. Instead, we will implement a system that alerts users if they attempt to refresh the page after uploading images, ensuring that progress is not lost while allowing users to upload more images without hitting storage limits.

## Acceptance Criteria
- Remove the use of session storage for holding uploaded images.
- Implement an alert that warns users if they try to refresh the page after uploading images, informing them that their progress will be lost.
- Ensure users can upload more images without facing the size limitations associated with session storage.
- Verify that the new solution enhances the user experience without causing disruptions to the upload process.

**Comment by SamuelPelletierEvraire** [comment]
@k-allagbe isn't this fix with the refactor?

**Comment by k-allagbe** [comment]
> @k-allagbe isn't this fix with the refactor?

Yes.
