### ISSUE TITLE
As a user, I want to be able to report an issue or request a feature from the frontend.

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#285]
## Description  

**Context**
As stated in #248 any frontend app should include a way for the users to report issues or ask for a feature.

**Problem Statement**
To respect standards, the frontend of FertiScan should give the ability to any user to report an issue. Because the AI Lab team want to make their workflow as simple as possible, when a user want to report an issue, the issue should be directly created on GitHub and should pass through the least possible app on its way from FertiScan to GitHub. But, the user cannot be simply redirected to GitHub as, to create an issue, they need to have a GitHub account.
Thanks to our office365 license we should be able to redirect the user to a Microsoft Form. The form might be generic for all of AI Lab's project and might be prefilled with informations depending on the application the user comes from. When submit is clicked, we can create an issue directly in GitHub by utilizing Microsoft Power Automate.
Mind that, as the GitHub repositories are public, sensitive data should not be included in the data (user name, email...).
Those information could be sent through email via the Power Automate workflow so the user can be contacted in case further information are needed

**Acceptance Criteria**

- [x] Fertiscan has a way to report issue and request feature
- [x] When a user report an issue or request a feature, an issue is created on the fertiscan project
- [x] The issue has a minimum of steps to be created from user click to github issue'
- [x] The user can be contacted after he created the issue
- [x] No sensitive information is available to the public

**Comment by SonOfLope** [comment]
FYI, a solution is under review outside of github.
