### ISSUE TITLE
As a dev, I want to set up a base project with Next.js, Zustand, and Material-UI

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/fertiscan-frontend#292]
## Description  

**Context**
We are starting our frontend project from scratch, transitioning from vanilla React to using Next.js, Zustand, and Material-UI. We want to ensure the project has a solid foundation so that the team can work in parallel efficiently. This base will include key configurations, folder structures, and tooling to standardize our development process.

**Problem Statement**
The base project needs to be set up with the core technologies and configurations to ensure consistency across the team, allowing us to develop features in parallel without conflicts.

## Acceptance Criteria
- Set up Next.js project with proper initialization.
- Define and implement a consistent folder structure.
- Integrate Zustand for global state management.
- Configure Material-UI with custom theming.
- Implement basic routing and navigation setup.
- Set up ESLint and Prettier for linting and formatting.
- Integrate Jest and React Testing Library for unit testing.
- Configure environment variable management using Next.js built-in features.
- Provide initial documentation with setup and contribution guidelines.
- Include sample components and pages for state management, routing, and Material-UI usage.
- Consider opting out of [Next.js telemetry](https://nextjs.org/telemetry): [How do I opt-out?](https://nextjs.org/telemetry#how-do-i-opt-out)

**Comment by SamuelPelletierEvraire** [comment]
@k-allagbe @Youllou  @ChromaticPanic 
Do we want to install middleware for log state change?

**Comment by ChromaticPanic** [comment]
> [@k-allagbe](https://github.com/k-allagbe) [@Youllou](https://github.com/Youllou) [@ChromaticPanic](https://github.com/ChromaticPanic) Do we want to install middleware for log state change?

This article recommends middleware for some scenarios like user authentication redirects https://blog.logrocket.com/guide-state-management-next-js/ [1]

Here is some discussion on the topic of handling state server side https://github.com/pmndrs/zustand/discussions/2200 [2]

For state within a page, state will still be handled client side. Not sure if currently we need to share state between pages? For data sharing between pages when using Next, my interpretation of the discussion in [2] is that there shouldn't be global state server side so any shared data will come from the database. It looks like they recommend useContext https://github.com/pmndrs/zustand/discussions/2200#discussioncomment-8395699

**Comment by k-allagbe** [comment]
I think that for simplicity we should avoid trying to handle states on server side. I'm not too familiar with that to be honest. I suggest as a first step that we handle components rendering client-side (like usual) along with the state management. Once we nail down the details, we render static components on server. What do you think?

**Comment by ChromaticPanic** [comment]
> I think that for simplicity we should avoid trying to handle states on server side. I'm not too familiar with that to be honest. I suggest as a first step that we handle components rendering client-side (like usual) along with the state management. Once we nail down the details, we render static components on server. What do you think?

I agree, that is a good strategy. As we add components and functionality to the nextjs branch we can review the components for design issues.
